### ISSUE TITLE
build: upgrade to solana-* 2.0

### ISSUE THREAD

**Issue by OliverNChalk** [LiteSVM/litesvm#93] opened 2024-10-01 14:31 UTC
Had a look at upgrading to 2.0 and the process seems pretty painful, wondering if you guys have had a look at what would be involved? Seems like a bunch of stuff has moved around + some APIs may have disappeared?

### Update

I now see: https://github.com/LiteSVM/litesvm/tree/solana-2

**Comment by sonicfromnewyoke** [comment] 2024-10-03 07:33
I believe this can be closed as the topic of the issue is currently cooking under the #76

**Closed** 2024-10-03 08:56 UTC
